### PR TITLE
Add option to not drop any columns due to the number of levels

### LINKED ISSUE #21: Add easy way to *not* drop any columns/levels
This would be useful when you know you want to keep a column but do not necessarily know how many groups there are or the counts per level. Could probably just pass in -1 to specify this.

### PR DESCRIPTION
**Pull request by gibsramen**
Closes #21

### CODE REVIEW

**Review by antgonza — APPROVED** [review]
Looks good to me, only comment is that perhaps `Must be > 1.`, should be `Must be > 1 or -1.`; what do you think?

**Comment by gibsramen** [comment]
The `Must be > 1` limitation is for the minimum count per level for which I don't think it makes sense to allow -1. We have to drop levels with only one count since we can't calculate an associated standard deviation for that "group". (Sorry if I'm misunderstanding your comment)

**Comment by antgonza** [comment]
Thank you; I just re-read the code and I realized that I was getting confused between `max_levels_per_category` and `min_count_per_level` but now I see the difference and I think is fine; would it be worth explaining why were the default values picked (min_count_per_level: 5 and min_count_per_level: 3)?

**Comment by gibsramen** [comment]
Yeah I think explaining the default choices is a good call.

**Pull request merged**
