### PR TITLE
Update interactive visualization with sorted effect sizes

### PR DESCRIPTION
**Pull request by gibsramen**
Visualization now includes two tabs - an "overview" of the dataset where the binary & multi-class categories are ranked by effect size and the "detailed" view with the metadata column selection view that is already implemented.

image

### CODE REVIEW

**Comment by gibsramen** [comment]
@ElDeveloper Is this the type of visualization you had in mind for the interactive component?

**Review by ElDeveloper — APPROVED** [review]
@gibsramen, this looks great! This is indeed the kind of plot that I thought would be great to include. The only missing part to match the figure in the current manuscript would be to allow users to select multiple categories to plot in the detailed layout. The trick here will be to make colors match between the overview and the detailed view.

**Comment by gibsramen** [comment]
Gotcha. Will likely require some JavaScript finagling but should be doable...

EDIT: Actually I think JS won't be required.

**Comment by gibsramen** [comment]
Merging this and working on the multiple categories issue in a separate branch. Thanks @ElDeveloper !!!

**Comment by ElDeveloper** [comment]
Happy to help wrangle JavaScript if needed. This strategy makes a lot of sense!

**Pull request merged**
