### PR TITLE
Allow selection of multiple columns in interactive visualization

### PR DESCRIPTION
**Pull request by gibsramen**
Can now select multiple columns for the power curve. Moves boxplot to a new tab where you can also view the scatter points. Also fixes issue where outliers weren't being shown on the boxplot.

image

image

TO DO:

- [x] Update README with new image
- [x] Add apostrophe to `Cohen's`

### CODE REVIEW

**Comment by gibsramen** [comment]
@ElDeveloper Does the layout look okay to you?

**Comment by ElDeveloper** [comment]
This is awesome, although the figure on the paper kinda nailed it. I think you want the effect-size barcharts (on the left)  faceted with their corresponding power curves (on the right), like you have in the figure of the manuscript. Only thing about that approach is that it is unclear what to do with the boxplots showing the actual data. In its current form how do you select what data to display on the right? Do you click on the legend or something like that? If that's the case, then the Overview and Detailed tabs can probably be merged into one tab that shows the curves and barcharts, and if you click on the legends or something else you get to visualize the boxplots for the corresponding categories (as a sort of first principles check).

**Comment by gibsramen** [comment]
Yeah I wasn't sure what to do with the boxplot. At the moment there's a selection for `Boxplot Column` in the control panel that determines which data is shown on that side. Dealing with legends in Bokeh is... difficult so I'd like to avoid interactivity on that front.

**Comment by ElDeveloper** [comment]
That should be fine then. Then maybe it would suffice to have the side-by-side barplot curves and at the bottom in a separate row the boxplot(?). Up to you.

**Pull request merged**
