### PR TITLE
Add option for bootstrapped effect sizes

### LINKED ISSUE #18: Add option for bootstrapping & CI
Could be useful to bootstrap differences and get a range of effect sizes

### PR DESCRIPTION
**Pull request by gibsramen**
Closes #18

Adds option to provide parameter `bootstrap_iterations` to calculate bootstrapped CIs. Reshuffles data with replacement to generate 95% CI.

Also refactors some of the `DataHandler` internals to clean up code. CC @dhakim87 who had the idea for the reorganization of `_bulk_power_analysis` such that we can drop the LRU caching.

TODO: Update docstrings

### CODE REVIEW

**Review by antgonza — APPROVED** [review]
Looks good to me, is this ok to merge?

**Comment by antgonza** [comment]
Ha! Just saw that this is a draft ..

**Comment by gibsramen** [comment]
No problem - gonna try this out on some real data to make sure it works in practice. Also wanna benchmark the performance a little bit since this changes a good deal of the internals.

**Comment by gibsramen** [comment]
Ok to merge still? Tested it out on the manuscript analysis and the results are the same and time difference is negligible or faster.

**Pull request merged**
